name: Issue Notifications

on:
  workflow_call:
    secrets:
      ACK_SLACK_WEBHOOK_URL:
        required: true
      ACK_ALERT_KEYWORDS:
        required: false
      ACK_REACTION_THRESHOLD:
        required: false
      ACK_COMMENT_THRESHOLD:
        required: false

    inputs:
      check_all_open_issues:
        required: false
        type: boolean
        default: true
      max_issues_to_check:
        required: false
        type: number
        default: 100
      issue_state:
        required: false
        type: string
        default: open

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Notification Action
        uses: joshdholtz/github-action-issue-ack@v17
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          slack_webhook_url: ${{ secrets.ACK_SLACK_WEBHOOK_URL }}

          # Keywords to raise alert
          title_keywords: ${{ secrets.ACK_ALERT_KEYWORDS }}

          # Excluded labels to silence notifications
          excluded_labels: "acknowledged"

          # Reaction and comment thresholds to raise alert
          reaction_threshold: ${{ secrets.ACK_REACTION_THRESHOLD }}
          comment_threshold: ${{ secrets.ACK_COMMENT_THRESHOLD }}
          
          # Batch checking configuration
          check_all_open_issues: ${{ inputs.check_all_open_issues }}
          max_issues_to_check: "100"
          issue_state: "open"

          # Custom prefixes
          new_issue_prefix: "🚨 New issue created on *{repo_name}*!"
          threshold_prefix: "📈 High-engagement issue on *{repo_name}*!"

          # Custom message
          message_template: |
            *{title}*
            Created: {created_ago}
            Reactions: {reactions} | Comments: {comments}
            {url}

          # Enable both notification types
          notify_on_create: "true"
          notify_on_threshold: "true"
